/* eslint-env mocha */
import { expect } from 'chai'
import IndexedFormulaOld from '../../src/indexed-formula-obj'
import Fetcher from '../../lib/fetcher'
import NamedNode from '../../lib/named-node'
import Literal from '../../lib/literal'

describe('Loading on object', () => {
  it('Fetching and loading will take ', (done) => {
    let kb = new IndexedFormulaOld()
    let fetcher = new Fetcher(kb, 30000)
    fetcher.load('file://D:/programming/Q2005.ttl')
      .then(() => {
        done()
        describe('queue in object', () => {
          it('Object queue will take', (donz) => {
            let a = []
            let n
            let q
            let p = new NamedNode('http://schema.org/description')
            n = new Literal('grafický symbol spojovaný s identitou organizace', 'cs')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('grafički znak ili simbol koji najčešće koriste komercijalna poduzeća, organizacije', 'hr')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal("scritta o simbolo che rappresenta un prodotto, un servizio, un'azienda o un'organizzazione", 'it')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('marca o emblema gràfic usat normalment per empreses comercials i organitzacions', 'ca')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('marca ou emblema gráfico usado geralmente por organizações e empresas comerciais', 'pt')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('סמליל של חברה, ארגון', 'he')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('企业、组织或产品所使用的标志', 'zh')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('企業、組織或產品所使用的標誌', 'zh-hant')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('graafinen merkki tai tunnus, jota kaupalliset yritykset ja järjestöt yleisesti käyttävät', 'fi')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('distintivo gráfico utilizado generalmente por organizaciones y empresas comerciales', 'es')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('afbeelding van een logo van een bedrijf of organisatie', 'nl')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('grapiko a marka wenno kayarigan a kadawyan nga inus-usar babaen dagiti komersial nga empresa, guglo ken dagiti produkto', 'ilo')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('企业、组织或产品所使用的标志', 'zh-cn')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('ग्राफ़िक चिह्न या प्रतीक जो सामान्यतः वाणिज्यिक उद्यमो, संगठनो और उत्पादो द्वारा प्रयोग किया जाता है', 'hi')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('σήμα ή σύμβολο που χρησιμοποιείται συνήθως από εμπορικές επιχειρήσεις, οργανισμούς και προϊόντα', 'el')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('marque graphique ou emblème communément utilisé par les entreprises commerciales et les organisations', 'fr')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('民間企業や組織で使用されるグラフィック・マークまたは標章', 'ja')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('企業、組織或產品所使用的標誌', 'zh-tw')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('Distintivu gráficu específicu que representa a una organización, empresa o productu', 'ast')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('grafisch gestaltetes Wortzeichen', 'de')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('企業、組織或產品所使用的標誌', 'zh-hk')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('graphic mark or emblem commonly used by commercial enterprises, organisations and products', 'en-ca')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('વ્યવસાયિક ઉદ્યોગ, સંગઠન અને ઉત્પાદ દ્વારા સામાન્ય રીતે વપરાતું ચિત્ર અથવા મુદ્રા', 'gu')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('grafisk mærke eller emblem, som generelt anvendes af virksomheder og organisationer', 'da')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('графічны сымбаль ці эмблема арганізацыі, прадпрыемства, установы, клюбу і да т. п.', 'be-tarask')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('grafisk märke eller emblem vanligen använt för företag, organisationer eller produkter', 'sv')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('grafika marko aŭ emblemo uzata de enterpreno, organizo aŭ produkto', 'eo')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('marca gràfica o emblema adupiratu da mprisi cummirciali o organizzazzioni', 'scn')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('ôfbylding fan in logo fan in bedriuw of organisaasje', 'fy')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('enpresa, erakunde edota produktu baten ikur grafikoa', 'eu')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('เครื่องหมายสัญลักษณ์ของกิจการ องค์กร และผลิตภัณฑ์', 'th')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('कुनै पनि संस्थाको परिचयात्मक चित्र', 'ne')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('항목 주제의 회사, 단체, 제품에 쓰인 그림 표식이나 그림 문장', 'ko')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('علامة أو شارة مستخدمة عادة من قبل المؤسسات التجارية والمنظمات وإلخ', 'ar')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('grafiskt merki ið vanliga verður nýtt av fyritøkum, feløgum og vørum', 'fo')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('bildefil med grafisk emblem for en bedrift, en organisasjon, et produkt eller lignende', 'nb')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('graficzny znak lub symbol używany do identyfikacji przedsiębiorstw, organizacji lub produktów', 'pl')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('企業、組織或產品所使用的標誌', 'zh-mo')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('企业、组织或产品所使用的标志', 'zh-my')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('企业、组织或产品所使用的标志', 'zh-sg')
            q = kb.match(null, p, n)
            a.push(q)
            n = new Literal('組織、公司或者產品嘅標誌檔案', 'yue ')
            q = kb.match(null, null, q)
            a.push(q)

            n = NamedNode.fromValue('http://www.wikidata.org/entity/P287')
            q = kb.match(n, null, null)
            expect(q).to.be.an('array')
            expect(a).to.be.an('array')
            donz()
            // console.log('1')
            // Promise.delay(500).then(() => {
            //   console.log('2')
            //   donz()
          // })
          })
        })
      })
  })
})
